#!/usr/bin/env python3
"""Generate compact 12x12 Chinese glyph bitmaps for OLED pause menu."""
from __future__ import annotations

import os
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parent
OUT = REPO / "shared_lib" / "display" / "OpenFIREdisplay_zh_glyphs.h"

STRINGS = [
    # Pause menu
    "中心校准", "保存设置", "画圈校准", "屏幕校准", "配置选择",
    "震动开关", "电磁开关", "发送Esc", "连发开关", "低键模式",
    "布局切换", "枪号", "枪号P1-P4", "摇杆模式", "模式切换",
    "游戏计时", "轴模式", "互换摇杆", "震动反馈", "反转X轴",
    "反转Y轴", "死区", "开", "关", "键鼠", "手柄", "MiSTer",
    "当前:键鼠", "当前:手柄", "当前:MiSTer", "低键:开", "低键:关",
    "摇杆", "十字", "方向键", "键盘键", "菱形", "方形",
    "无符号", "有符号", "反转", "正常", "反", "正", "无",
    # Top panel / status
    "配置:", "使用", "校准:", "校准就绪", "USB模式", "等待USB",
    "连接就绪", "童锁就绪", "USB已连接", "模式:手柄", "模式:键鼠",
    "模式:MiSTer", "画圈:旋转", "松开回中", "画圈:完成", "画圈:偏弱",
    "中心已校", "已发Esc", "摇杆:手柄", "摇杆:十字", "摇杆:按键",
    "震动:开", "震动:关", "电磁:开", "电磁:关", "游戏时间到",
    # Full screens
    "欢迎!", "扣扳机", "扣扳机开始校准", "红外测试", "保存配置",
    "保存中...", "保存", "成功", "失败", "温度:", "故障",
    # Profile picker / idle
    "A>", "B>", "始>", "选>", "菱", "方", "错", "童锁?",
    # Formatted snippets
    "枪号P1", "布局:菱形", "连发:开", "低键:关", "摇杆:十字",
    "按键:WASD", "死区30%", "轴:无符号", "互换:开", "震动:关",
    "震动:无", "计时:关", "计时5分", "X轴:反转", "Y轴:正常",
    "X:反", "Y:正",     "计时20分",
    # Wireless / dongle / pedal
    "OpenFIRE接收器", "RF嗅探ch", "WiFi扫描", "优选信道", "请稍候",
    "信道", "配对", "请开光枪", "ESP-NOW监听", "射频已连接",
    "等待数据流", "等待踏板", "玩家:", "踏台搜索", "秒",
    "等待连接", "已选", "连接中", "搜索中", "器:",
    "踏", "台", "嗅", "探", "扫", "描", "优", "选", "稍", "候",
    "对", "光", "射", "频", "数", "据", "流", "踏", "板", "家",
    "接", "收", "器",
    # ASCII punctuation used in mixed strings
    ":", "%", "!", ".", "?", "P", "W", "A", "S", "D", "E", "s", "c",
    "M", "i", "T", "e", "r", "l", "u", ">", "0", "1", "2", "3", "4",
    "5", "6", "7", "8", "9",
]

FONT_CANDIDATES = [
    r"C:\Windows\Fonts\msyh.ttc",
    r"C:\Windows\Fonts\simsun.ttc",
    r"C:\Windows\Fonts\simhei.ttf",
    "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
]

CELL_W = 12
CELL_H = 12
BYTES_PER_GLYPH = CELL_H * 2


def load_font(size: int = 11) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for path in FONT_CANDIDATES:
        if os.path.isfile(path):
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def render_glyph(ch: str, font) -> list[int]:
    img = Image.new("1", (CELL_W, CELL_H), 0)
    draw = ImageDraw.Draw(img)
    bbox = draw.textbbox((0, 0), ch, font=font)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    x = max(0, (CELL_W - tw) // 2) - bbox[0]
    y = max(0, (CELL_H - th) // 2) - bbox[1]
    draw.text((x, y), ch, font=font, fill=1)

    out: list[int] = []
    for row in range(CELL_H):
        b0 = 0
        b1 = 0
        for col in range(CELL_W):
            bit = 1 if img.getpixel((col, row)) else 0
            if col < 8:
                b0 |= bit << (7 - col)
            else:
                b1 |= bit << (15 - col)
        out.extend([b0, b1])
    return out


def main() -> None:
    font = load_font(11)
    chars = []
    seen = set()
    for s in STRINGS:
        for ch in s:
            if ch not in seen:
                seen.add(ch)
                chars.append(ch)

    glyphs = {ch: render_glyph(ch, font) for ch in chars}

    lines = [
        "/* Auto-generated by scripts/gen_zh_menu_glyphs.py - do not edit. */",
        "#ifndef _OPENFIREDISPLAY_ZH_GLYPHS_H_",
        "#define _OPENFIREDISPLAY_ZH_GLYPHS_H_",
        "",
        "#include <stdint.h>",
        "",
        "#define ZH_GLYPH_W 12",
        "#define ZH_GLYPH_H 12",
        f"#define ZH_GLYPH_BYTES {BYTES_PER_GLYPH}",
        f"#define ZH_GLYPH_COUNT {len(chars)}",
        "",
        "typedef struct {",
        "    uint8_t key[3];",
        "    uint8_t key_len;",
        "    uint8_t data[ZH_GLYPH_BYTES];",
        "} ZhGlyphEntry;",
        "",
        "static const ZhGlyphEntry kZhGlyphs[ZH_GLYPH_COUNT] = {",
    ]

    for ch in chars:
        data = ", ".join(f"0x{b:02x}" for b in glyphs[ch])
        key = ch.encode("utf-8")
        key_bytes = ", ".join(f"0x{b:02x}" for b in key)
        pad = ", 0x00" * (3 - len(key))
        lines.append(
            f"    {{ {{{key_bytes}{pad}}}, {len(key)}, {{ {data} }} }}, /* {ch} */"
        )

    lines.extend([
        "};",
        "",
        "#endif /* _OPENFIREDISPLAY_ZH_GLYPHS_H_ */",
        "",
    ])

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(chars)} glyphs)")


if __name__ == "__main__":
    main()
