; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = rpipico   ;Raspberry Pi Pico    
;default_envs = rpipicow  ;Raspberry Pi Pico W    
;default_envs = rpipico2  ;Raspberry Pi Pico 2    
;default_envs = rpipico2w ;Raspberry Pi Pico 2 W  
default_envs = ESP32_S3_WROOM1_DevKitC_1_N16R8 ;ESP32S3 Wroom - FLASH 16Mb (QUAD spi - qio) PSRAM 8Mb (OCTAL spi - opi) - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3 Rev 0
;default_envs = ESP32_S3_WROOM1_DevKitC_1_N8R2  ;ESP32S3 Wroom - FLASH 8Mb  (QUAD spi - qio) PSRAM 2Mb (QUAD spi - qio)  - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3 Rev 0
;default_envs = WAVESHARE_ESP32_S3_PICO         ;ESP32S3 Pico  - FLASH 16Mb (QUAD spi - qio) PSRAM 2Mb (QUAD spi - qio)  - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3R2
;default_envs = WAVESHARE_ESP32_S3_ZERO_N8R8    ;ESP32S3 Mini  - FLASH 8Mb  (QUAD spi - qio) PSRAM 8Mb (OCTAL spi - opi) - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3R2
;default_envs = WAVESHARE_ESP32_S3_ZERO_N4R2    ;ESP32S3 Mini  - FLASH 4Mb  (QUAD spi - qio) PSRAM 2Mb (QUAD spi - qio)  - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3R2

; Le impostazioni globali delle cartelle vanno qui!
boards_dir = ../shared_boards

[env]

[esp32]

platform = https://github.com/pioarduino/platform-espressif32.git#55.03.38-1 ; Arduino Release v3.3.8 based on ESP-IDF v5.5.4
;platform = https://github.com/pioarduino/platform-espressif32.git#55.03.38 ; Arduino Release v3.3.8 based on ESP-IDF v5.5.4
; dalla versione 55.03.38 serve la versione del core di Platformio 6.1.19 - (usare dal terminale di PlatformIO Core CLI il comando:pio upgrade) https://github.com/platformio/platformio-core/releases/tag/v6.1.19
;;;platform = https://github.com/pioarduino/platform-espressif32.git#55.03.37 ; Arduino Release v3.3.7 based on ESP-IDF v5.5.2.260206
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip ; Arduino Release v3.3.2 based on ESP-IDF v5.5.1.250929
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip ; stable

platform_packages = 
lib_deps = 
	Adafruit TinyUSB Library = https://github.com/adafruit/Adafruit_TinyUSB_Arduino.git#3.7.5
	;Adafruit TinyUSB Library = https://github.com/adafruit/Adafruit_TinyUSB_Arduino.git#3.7.4
	;Adafruit TinyUSB Library@^3.7.3
	${common.lib_deps}
lib_ignore =

[rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#develop
platform_packages =
	framework-arduinopico @ https://github.com/earlephilhower/arduino-pico.git#5.5.1
lib_deps = 
	${common.lib_deps}
lib_ignore = OpenFIRE_Wireless

[common]
lib_deps = 
	adafruit/Adafruit SSD1306@^2.5.16
	Adafruit NeoPixel = https://github.com/adafruit/Adafruit_NeoPixel.git#1.15.4
	;adafruit/Adafruit NeoPixel@1.15.2
	adafruit/Adafruit GFX Library@1.12.6
	;adafruit/Adafruit GFX Library@^1.12.4
	adafruit/Adafruit BusIO@1.17.4
	LovyanGFX Library = https://github.com/lovyan03/LovyanGFX.git#1.2.19
	;lovyan03/LovyanGFX@^1.2.7
	;LovyanGFX Library = https://github.com/lovyan03/LovyanGFX.git#develop
	;LovyanGFX Library = https://github.com/lovyan03/LovyanGFX.git#2689b7c12e384558991d324e19bc67782f986551  ; ramo develop - 13 dic 2025

build_flags = 
	-D GUN
	-D PLAYER_NUMBER=1
	-D USES_DISPLAY
	-D USES_SOLENOID
	-D USES_RUMBLE
	;-D USES_SWITCHES
	-D MAMEHOOKER
	-D USES_ANALOG
	-D CUSTOM_NEOPIXEL
	-D FOURPIN_LED
	-D DUAL_CORE
	-D USES_TEMP
	-D USE_TINYUSB
	-D USE_LOVYAN_GFX
	-D USE_SQUARE_ADVANCED
	-D USE_PERSPECTIVE_ADVANCED
	-D USE_MULTI_ONE_EURO_FILTER
	-D CLOCK_CAM_WII
	-std=gnu++17
	-std=gnu17
	-O2
build_unflags = 
	-std=gnu++11
	-std=gnu11
	-Og

[env:ESP32_S3_WROOM1_DevKitC_1_N16R8]
platform = ${esp32.platform}
board = ESP32-S3-WROOM-1-DevKitC-1-N16R8
;board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 9600 ;115200
lib_deps = ${esp32.lib_deps}
lib_ignore = ${esp32.lib_ignore}
build_unflags = 
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
build_flags = 
	-D NEOPIXEL_PIN=48          ; neopixel integrato sulla board - commentare per disabilitarlo ; se si attiva si ail custom che quello sulla board funzioneranno entrambi
	;-D NEOPIXEL_ENABLEPIN ; il neopixel sulla board non ha bisogna di pin di abilitazione, in caso dovesse servire inserire il pin
	;-D DISABLE_FS_H_WARNING
	-D ARDUINO_ESP32_S3_WROOM1_DevKitC_1_N16R8
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 68 il range è da 8 a 84 che corrisponde ad un valore x4 di db tra 2 a 21 db
	;-D OPENFIRE_ESPNOW_WIFI_POWER_AUTO ; definirlo se si vuole che la potenza di trasmissione si regoli in automatico ; al momento uisato solo per test, probabilmente inutile
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
	-D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	${common.build_flags}
;upload_protocol = esp-builtin
platform_packages = ${esp32.platform_packages}
;board_build.partitions = default_8MB.csv
; ===========
;board_build.arduino.memory_type = qio_qspi
;board_build.arduino.memory_type = qio_opi
;;board_build.flash_mode = qio
;;board_build.psram_type = opi
;board_build.psram_type = qspi
;;board_build.psram_size = 8MB
;;board_upload.flash_size = 16MB
;;board_upload.maximum_size = 16777216
;;board_build.extra_flags = 
  ;;-DBOARD_HAS_PSRAM
  ;;-DPSRAM_SIZE=8MB
  ;-DCFG_TUD_CDC_RX_BUFSIZE=2048
  ;-DCFG_TUD_CDC_TX_BUFSIZE=64
; ===========
board_build.partitions = ../shared_boards/partitions/default_OF_16MB.csv
board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = 
	../shared_lib
	;./boards
lib_ldf_mode = chain
lib_compat_mode = strict

[env:ESP32_S3_WROOM1_DevKitC_1_N8R2]
platform = ${esp32.platform}
board = ESP32-S3-WROOM-1-DevKitC-1-N8R2
;board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 9600 ;115200
lib_deps = ${esp32.lib_deps}
lib_ignore = ${esp32.lib_ignore}
build_unflags = 
	-DARDUINO_USB_MODE=1
	;-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
build_flags = 
	-D NEOPIXEL_PIN=48          ; neopixel integrato sulla board - commentare per disabilitarlo ; se si attiva si ail custom che quello sulla board funzioneranno entrambi
	;-D NEOPIXEL_ENABLEPIN ; il neopixel sulla board non ha bisogna di pin di abilitazione, in caso dovesse servire inserire il pin
	;-D DISABLE_FS_H_WARNING
	-D ARDUINO_ESP32_S3_WROOM1_DevKitC_1_N8R2
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 68 il range è da 8 a 84 che corrisponde ad un valore x4 di db tra 2 a 21 db
	;-D OPENFIRE_ESPNOW_WIFI_POWER_AUTO ; definirlo se si vuole che la potenza di trasmissione si regoli in automatico ; al momento uisato solo per test, probabilmente inutile
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
	-D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	${common.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_8MB.csv
board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_S3_PICO]
platform = ${esp32.platform}
board = WAVESHARE-ESP32-S3-PICO-N16R2
framework = arduino
monitor_speed = 115200
lib_deps = ${esp32.lib_deps}
lib_ignore = ${esp32.lib_ignore}
build_unflags = 
	-DARDUINO_USB_MODE=1
	;-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
build_flags = 
	-D NEOPIXEL_PIN=21     ; neopixel integrato sulla board - commentare per disabilitarlo
	;-D NEOPIXEL_ENABLEPIN ; il neopixel sulla board non ha bisogna di pin di abilitazione, in caso dovesse servire inserire il pin
	;-D DISABLE_FS_H_WARNING
	-D ARDUINO_WAVESHARE_ESP32_S3_PICO
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 68 il range è da 8 a 84 che corrisponde ad un valore x4 di db tra 2 a 21 db
	;-D OPENFIRE_ESPNOW_WIFI_POWER_AUTO ; definirlo se si vuole che la potenza di trasmissione si regoli in automatico ; al momento uisato solo per test, probabilmente inutile
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
	-D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	${common.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_16MB.csv
board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_S3_ZERO_N8R8]
platform = ${esp32.platform}
board = WAVESHARE-ESP32-S3-ZERO-N8R8
framework = arduino
monitor_speed = 115200
lib_deps = ${esp32.lib_deps}
lib_ignore = ${esp32.lib_ignore}
build_unflags = 
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
build_flags = 
	-D NEOPIXEL_PIN=21     ; neopixel integrato sulla board - commentare per disabilitarlo
	;-D NEOPIXEL_ENABLEPIN ; il neopixel sulla board non ha bisogna di pin di abilitazione, in caso dovesse servire inserire il pin
	;-D DISABLE_FS_H_WARNING
	-D ARDUINO_WAVESHARE_ESP32_S3_ZERO_N8R8
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 68 il range è da 8 a 84 che corrisponde ad un valore x4 di db tra 2 a 21 db
	;-D OPENFIRE_ESPNOW_WIFI_POWER_AUTO ; definirlo se si vuole che la potenza di trasmissione si regoli in automatico ; al momento uisato solo per test, probabilmente inutile
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
	-D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	${common.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_8MB.csv
board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_S3_ZERO_N4R2]
platform = ${esp32.platform}
board = WAVESHARE-ESP32-S3-ZERO-N4R2
framework = arduino
monitor_speed = 115200
lib_deps = ${esp32.lib_deps}
lib_ignore = ${esp32.lib_ignore}
build_unflags = 
	-DARDUINO_USB_MODE=1
	;-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
build_flags = 
	-D NEOPIXEL_PIN=21     ; neopixel integrato sulla board - commentare per disabilitarlo
	;-D NEOPIXEL_ENABLEPIN ; il neopixel sulla board non ha bisogna di pin di abilitazione, in caso dovesse servire inserire il pin
	;-D DISABLE_FS_H_WARNING
	-D ARDUINO_WAVESHARE_ESP32_S3_ZERO_N4R2
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 68 il range è da 8 a 84 che corrisponde ad un valore x4 di db tra 2 a 21 db
	;-D OPENFIRE_ESPNOW_WIFI_POWER_AUTO ; definirlo se si vuole che la potenza di trasmissione si regoli in automatico ; al momento uisato solo per test, probabilmente inutile
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
	-D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	${common.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_4MB.csv
board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict


[env:rpipicow]
platform = ${rp2040.platform}
framework = arduino
board = rpipicow
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 9600
monitor_port = COM3
upload_protocol = picotool
build_type = release
lib_deps = 	${rp2040.lib_deps}
lib_ignore = ${rp2040.lib_ignore}
build_unflags = 
	-DARDUINO_USB_MODE=1
	${common.build_unflags}
build_flags = 
	-D ARDUINO_RASPBERRY_PI_PICO_W
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
	${common.build_flags}
platform_packages = ${rp2040.platform_packages}
board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:rpipico]
platform = ${rp2040.platform}
framework = arduino
board = rpipico
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 9600
monitor_port = COM3
upload_protocol = picotool
build_type = release
lib_deps = 	${rp2040.lib_deps}
lib_ignore = 
    HID_Bluetooth
    PicoBluetoothHID
	${rp2040.lib_ignore}
build_unflags = 
	-DARDUINO_USB_MODE=1
	${common.build_unflags}
build_flags = 
	-D ARDUINO_RASPBERRY_PI_PICO
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	${common.build_flags}
platform_packages = ${rp2040.platform_packages}
board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict


[env:rpipico2w]
platform = ${rp2040.platform}
framework = arduino
board = rpipico2w
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 9600
monitor_port = COM3
upload_protocol = picotool
build_type = release
lib_deps = 	${rp2040.lib_deps}
lib_ignore = ${rp2040.lib_ignore}
build_unflags = 
	-DARDUINO_USB_MODE=1
	${common.build_unflags}
build_flags = 
	-D ARDUINO_RASPBERRY_PI_PICO_2W
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
	${common.build_flags}
platform_packages = ${rp2040.platform_packages}
board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:rpipico2]
platform = ${rp2040.platform}
framework = arduino
board = rpipico2
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 9600
monitor_port = COM3
upload_protocol = picotool
build_type = release
lib_deps = 	${rp2040.lib_deps}
lib_ignore = 
    HID_Bluetooth
    PicoBluetoothHID
	${rp2040.lib_ignore}
build_unflags = 
	-DARDUINO_USB_MODE=1
	${common.build_unflags}
build_flags = 
	-D ARDUINO_RASPBERRY_PI_PICO_2
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	${common.build_flags}
platform_packages = ${rp2040.platform_packages}
board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict
