#ifndef OPENFIRE_PEDAL_VERSION_H
#define OPENFIRE_PEDAL_VERSION_H

// Versione attuale
#define OPENFIRE_PEDAL_VERSION 6.1
///////#define OPENFIRE_CODENAME "Dawn Sigma rc2"
//#define GIT_HASH
#define OPENFIRE_PEDAL_VERSION_MAJOR 6
#define OPENFIRE_PEDAL_VERSION_MINOR 1
#define OPENFIRE_PEDAL_VERSION_PATCH 0
#define OPENFIRE_PEDAL_VERSION_TYPE "rc2"  // Per indicare pre-release (alpha, beta, RC(Release Candidate), stable)

// Stringa di versione attuale
#define OPENFIRE_PEDAL_VERSION_STRING (String(OPENFIRE_PEDAL_VERSION_MAJOR) + "." + String(OPENFIRE_PEDAL_VERSION_MINOR) + "." + String(OPENFIRE_PEDAL_VERSION_PATCH)+ "-" + OPENFIRE_PEDAL_VERSION_TYPE)
//#define OPENFIRE_VERSION_STRING TU_STRING(OPENFIRE_VERSION_MAJOR) "." TU_STRING(OPENFIRE_VERSION_MINOR) "." TU_STRING(OPENFIRE_VERSION_PATCH)

// Numero combinato della versione attuale
#define OPENFIRE_PEDAL_VERSION_NUMBER (OPENFIRE_PEDAL_VERSION_MAJOR * 10000 + OPENFIRE_PEDAL_VERSION_MINOR * 100 + OPENFIRE_PEDAL_VERSION_PATCH)

// =============== ultima versione compatibile =================================

// Ultima versione precedente compatibile
#define OPENFIRE_PEDAL_COMPATIBLE_MAJOR 4
#define OPENFIRE_PEDAL_COMPATIBLE_MINOR 3
#define OPENFIRE_PEDAL_COMPATIBLE_PATCH 2

// Stringa di versione compatibile precedente
#define OPENFIRE_PEDAL_COMPATIBLE_STRING (String(OPENFIRE_PEDAL_COMPATIBLE_MAJOR) + "." + String(OPENFIRE_PEDAL_COMPATIBLE_MINOR) + "." + String(OPENFIRE_PEDAL_COMPATIBLE_PATCH))
//#define OPENFIRE_PEDAL_COMPATIBLE_STRING TU_STRING(OPENFIRE_PEDAL_COMPATIBLE_MAJOR) "." TU_STRING(OPENFIRE_PEDAL_COMPATIBLE_MINOR) "." TU_STRING(OPENFIRE_PEDAL_COMPATIBLE_PATCH)

// Numero combinato della versione precedente compatibile
#define OPENFIRE_PEDAL_COMPATIBLE_NUMBER (OPENFIRE_PEDAL_COMPATIBLE_MAJOR * 10000 + OPENFIRE_PEDAL_COMPATIBLE_MINOR * 100 + OPENFIRE_PEDAL_COMPATIBLE_PATCH)

#endif  // OPENFIRE_PEDAL_VERSION_H
