name=LGFX_Config
version=1.0.0
author=Alessandro Satanassi
maintainer=Alessandro Satanassi <@alessandro@cittini.it>
sentence=Configurazioni per diosplat TFT
paragraph=Configurazioni per display TFT per Lovely
category=display
url=https://github.com/SeongGino/ir-light-gun-plus/tree/plus/libraries/TinyUSB_Devices
architectures=*
includes=LGFX_096_SSD1306_64x128.hpp
