; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = ESP32_S3_WROOM1_DevKitC_1_N16R8 ;ESP32S3 Wroom - FLASH 16Mb (QUAD spi - qio) PSRAM 8Mb (OCTAL spi - opi) - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3 Rev 0
;default_envs = ESP32_S3_WROOM1_DevKitC_1_N8R2  ;ESP32S3 Wroom - FLASH 8Mb  (QUAD spi - qio) PSRAM 2Mb (QUAD spi - qio)  - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3 Rev 0
;default_envs = WAVESHARE_ESP32_S3_PICO         ;ESP32S3 Pico  - FLASH 16Mb (QUAD spi - qio) PSRAM 2Mb (QUAD spi - qio)  - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3R2
;default_envs = WAVESHARE_ESP32_S3_ZERO_N8R8    ;ESP32S3 Mini  - FLASH 8Mb  (QUAD spi - qio) PSRAM 8Mb (OCTAL spi - opi) - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3R2
default_envs = WAVESHARE_ESP32_S3_ZERO_N4R2    ;ESP32S3 Mini  - FLASH 4Mb  (QUAD spi - qio) PSRAM 2Mb (QUAD spi - qio)  - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3R2
;default_envs = WAVESHARE_ESP32_C3_ZERO_N4      ;ESP32C3 Mini  - FLASH 4Mb  (QUAD spi - qio) NO PSRAM                    - 400KB SRAM, 384KB ROM - RISC-V 32-bit single-core at 160MHz    - Adopts ESP32-C3FH4
;default_envs = ESP32_WROOM_32                  ;ESP32 Wroom   - FLASH 4Mb  (QUAD spi - qio) NO PSRAM                    - 520KB SRAM, 448KB ROM - Xtensa 32-bit LX6 dual-core at 240 MHz - Adopts ESP32

; Le impostazioni globali delle cartelle vanno qui!
boards_dir = ../shared_boards

[env]

[esp32]
platform_packages = 

[common]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.38-1 ; Arduino Release v3.3.8 based on ESP-IDF v5.5.4

lib_deps = 
	Adafruit TinyUSB Library = https://github.com/adafruit/Adafruit_TinyUSB_Arduino.git#3.7.7

build_unflags = 
	-std=gnu++11
	-std=gnu11
    -Og

build_flags = 
    -D PEDAL
	-D USE_TINYUSB
	-std=gnu++17
	-std=gnu17
    -O2
	
[pin_ESP32_S3_WROOM1_DevKitC_1]

;                                          SER     OTG
;                                      ___(USB)___(USB)___  
;                                (GND) |x)  1  PIN  44 (x| (GND)
;                                (GND) |x)  2       43 (-| (5V OUT-IN)
;                            (GPIO 19) |-)  3       42 (-| (GPIO 14)
;                            (GPIO 20) |-)  4       41 (-| (GPIO 13) 
;                            (GPIO 21) |-)  5       40 (-| (GPIO 12) 
;                            (GPIO 47) |-)  6       39 (-| (GPIO 11) 
;                            (GPIO 48) |-)  7       38 (-| (GPIO 10) 
;                            (GPIO 45) |-)  8       37 (-| (GPIO 09) 
;                            (GPIO 00) |-)  9       36 (-| (GPIO 46)
;                            (GPIO 35) |-) 10       35 (-| (GPIO 03)
;                            (GPIO 36) |-) 11       34 (-| (GPIO 08) 
;                            (GPIO 37) |-) 12       33 (-| (GPIO 18) 
;                            (GPIO 38) |-) 13       32 (-| (GPIO 17) 
;                            (GPIO 39) |-) 14       31 (-| (GPIO 16) 
;                            (GPIO 40) |-) 15       30 (-| (GPIO 15) 
;                            (GPIO 41) |-) 16       29 (-| (GPIO 07)
;                            (GPIO 42) |-) 17       28 (-| (GPIO 06)
;                            (GPIO 02) |-) 18       27 (-| (GPIO 05)
;                            (GPIO 01) |-) 19       26 (-| (GPIO 04)
;                                 (RX) |-) 20       25 (-| (RST)
;                                 (TX) |-) 21       24 (p| (3V3 OUT)
;                                (GND) |x) 22  PIN  23 (p| (3V3 OUT)
;                                      |_________________|  
;										   | ANTENNA |
;										   |_________|

build_unflags = 

build_flags = 
    -D PIN_LED1=4    ; gpio output per LED
    -D PIN_LED2=5    ; gpio outpud per LED
    -D PIN_LED3=6    ; gpio output per LED
    -D PIN_LED4=7    ; gpio output per LED
	-D PIN_PEDAL=8   ; gpio input per button
	-D PIN_PEDAL2=9  ; gpio input per button

[pin_WAVESHARE_ESP32_S3_PICO]

;                                     ______(*USB*)______     
;                           (GPIO 11) |-)  1  PIN  40 (-| (VBUS)
;                           (GPIO 12) |-)  2       39 (-| (VSYS)
;                               (GND) |x)  3       38 (x| (GND)     --> GND COMMON
;                           (GPIO 13) |-)  4       37 (x| (EN)
;                           (GPIO 14) |-)  5       36 (p| (3V3 OUT)                    
;                           (GPIO 15) |-)  6       35 (x| (GPIO 10)   
;                           (GPIO 16) |-)  7       34 (-| (GPIO 09) <-- SWITCH PEDAL2
;                               (GND) |x)  8       33 (x| (GND) 
;                           (GPIO 17) |-)  9       32 (-| (GPIO 08) <-- SWITCH PEDAL1
;                           (GPIO 18) |-) 10       31 (-| (GPIO 07) --> LED4
;                           (GPIO 33) |-) 11       30 (x| (RUN)
;                           (GPIO 34) |-) 12       29 (-| (GPIO 06) --> LED3
;                               (GND) |x) 13       28 (x| (GND)
;                           (GPIO 35) |-) 14       27 (-| (GPIO 05) --> LED2
;                           (GPIO 36) |-) 15       26 (-| (GPIO 04) --> LED1
;                           (GPIO 37) |-) 16       25 (-| (GPIO 02)
;                           (GPIO 38) |-) 17       24 (-| (GPIO 01)
;                               (GND) |x) 18       23 (x| (GND)
;                           (GPIO 39) |-) 19       22 (-| (GPIO 41)
;                           (GPIO 40) |-) 20  PIN  21 (-| (GPIO 42)
;                                     |_________________|


build_unflags = 

build_flags = 
    -D PIN_LED1=4    ; gpio output per LED
    -D PIN_LED2=5    ; gpio outpud per LED
    -D PIN_LED3=6    ; gpio output per LED
    -D PIN_LED4=7    ; gpio output per LED
	-D PIN_PEDAL=8   ; gpio input per button
	-D PIN_PEDAL2=9  ; gpio input per button

[pin_WAVESHARE_ESP32_S3_ZERO]

;                                     ______(*USB*)______     
;                                (5V) |-)  1  PIN  18 (-| (TX)
;          GND COMMON   <--     (GND) |x)  2       17 (-| (RX)
;                           (3V3 OUT) |p)  3       16 (-| (GPIO 13)
;                           (GPIO 01) |-)  4       15 (-| (GPIO 12)
;                           (GPIO 02) |-)  5       14 (-| (GPIO 11)    
;                           (GPIO 03) |-)  6       13 (-| (GPIO 10)   
;                 LED1  <-- (GPIO 04) |-)  7       12 (-| (GPIO 09) <-- SWITCH PEDAL2
;                 LED2  <-- (GPIO 05) |-)  8       11 (-| (GPIO 08) <-- SWITCH PEDAL
;                 LED3  <-- (GPIO 06) |-)  9  PIN  10 (-| (GPIO 07) --> LED4
;                                     |_________________|

build_unflags = 

build_flags = 
    -D PIN_LED1=4    ; gpio output per LED
    -D PIN_LED2=5    ; gpio outpud per LED
    -D PIN_LED3=6    ; gpio output per LED
    -D PIN_LED4=7    ; gpio output per LED
	-D PIN_PEDAL=8   ; gpio input per button
	-D PIN_PEDAL2=9  ; gpio input per button

[pin_WAVESHARE_ESP32_C3_ZERO]
build_unflags = 

build_flags = 
    -D PIN_LED1=4
    -D PIN_LED2=5
    -D PIN_LED3=6
    -D PIN_LED4=7
	-D PIN_PEDAL=10
	-D PIN_PEDAL2=3

[pin_ESP32_WROOM_32]
build_unflags = 

build_flags = 
    -D PIN_LED1=25    ; GPIO 25 (Output sicuro)
    -D PIN_LED2=26    ; GPIO 26 (Output sicuro)
    -D PIN_LED3=27    ; GPIO 27 (Output sicuro)
    -D PIN_LED4=14    ; GPIO 14 (Output sicuro)
    -D PIN_PEDAL=32   ; GPIO 32 (Input con Pull-up interno)
    -D PIN_PEDAL2=33  ; GPIO 33 (Input con Pull-up interno)

[env:ESP32_S3_WROOM1_DevKitC_1_N16R8]
platform = ${common.platform}
;board = esp32-s3-devkitc-1
board = ESP32-S3-WROOM-1-DevKitC-1-N16R8
framework = arduino
monitor_speed = 9600 ;115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	;-D ARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${pin_ESP32_S3_WROOM1_DevKitC_1.build_unflags}
build_flags = 
	-D ARDUINO_ESP32_S3_WROOM1_DevKitC_1_N16R8
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	;-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	;-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${pin_ESP32_S3_WROOM1_DevKitC_1.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_16MB.csv
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:ESP32_S3_WROOM1_DevKitC_1_N8R2]
platform = ${common.platform}
;board = esp32-s3-devkitc-1
board = ESP32-S3-WROOM-1-DevKitC-1-N8R2
framework = arduino
monitor_speed = 9600 ;115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	;-D ARDUINO_USB_MODE=1
    ;-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${pin_ESP32_S3_WROOM1_DevKitC_1.build_unflags}
build_flags = 
	-D ARDUINO_ESP32_S3_WROOM1_DevKitC_1_N8R2
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	;-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	;-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${pin_ESP32_S3_WROOM1_DevKitC_1.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_8MB.csv
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_S3_PICO]
platform = ${common.platform}
board = WAVESHARE-ESP32-S3-PICO-N16R2
;board = ESP32-S3-WROOM-1-DevKitC-1-N16R8
framework = arduino
monitor_speed = 9600 ;115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	;-D ARDUINO_USB_MODE=1
    ;-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${pin_WAVESHARE_ESP32_S3_PICO.build_unflags}
build_flags = 
	-D ARDUINO_WAVESHARE_ESP32_S3_PICO
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	;-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${pin_WAVESHARE_ESP32_S3_PICO.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_16MB.csv
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_S3_ZERO_N8R8]
platform = ${common.platform}
board = WAVESHARE-ESP32-S3-ZERO-N8R8
framework = arduino
monitor_speed = 115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	;-D ARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${pin_WAVESHARE_ESP32_S3_ZERO.build_unflags}
build_flags = 
	-D ARDUINO_WAVESHARE_ESP32_S3_ZERO_N8R8
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	;-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	;-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${pin_WAVESHARE_ESP32_S3_ZERO.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_8MB.csv
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_S3_ZERO_N4R2]
platform = ${common.platform}
board = WAVESHARE-ESP32-S3-ZERO-N4R2
framework = arduino
monitor_speed = 115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	;-D ARDUINO_USB_MODE=1
    ;-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${pin_WAVESHARE_ESP32_S3_ZERO.build_unflags}
build_flags = 
	-D ARDUINO_WAVESHARE_ESP32_S3_ZERO_N4R2
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	;-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	;-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${pin_WAVESHARE_ESP32_S3_ZERO.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_4MB.csv
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_C3_ZERO_N4]
platform = ${common.platform}
board = WAVESHARE-ESP32-C3-ZERO-N4
framework = arduino
monitor_speed = 115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	;-D ARDUINO_USB_MODE=1
    ;-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${pin_WAVESHARE_ESP32_C3_ZERO.build_unflags}
build_flags = 
	-D ARDUINO_WAVESHARE_ESP32_C3_ZERO_N4
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	;-D ARDUINO_USB_MODE=0
	;-D ARDUINO_USB_CDC_ON_BOOT=1
	;-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${pin_WAVESHARE_ESP32_C3_ZERO.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_4MB.csv
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict