; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = ESP32_S3_WROOM1_DevKitC_1_N16R8 ;ESP32S3 Wroom - FLASH 16Mb (QUAD spi - qio) PSRAM 8Mb (OCTAL spi - opi) - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3 Rev 0
;default_envs = ESP32_S3_WROOM1_DevKitC_1_N8R2  ;ESP32S3 Wroom - FLASH 8Mb  (QUAD spi - qio) PSRAM 2Mb (QUAD spi - qio)  - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3 Rev 0
;default_envs = WAVESHARE_ESP32_S3_PICO         ;ESP32S3 Pico  - FLASH 16Mb (QUAD spi - qio) PSRAM 2Mb (QUAD spi - qio)  - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3R2
;default_envs = WAVESHARE_ESP32_S3_ZERO_N8R8    ;ESP32S3 Mini  - FLASH 8Mb  (QUAD spi - qio) PSRAM 8Mb (OCTAL spi - opi) - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3R2
default_envs = WAVESHARE_ESP32_S3_ZERO_N4R2    ;ESP32S3 Mini  - FLASH 4Mb  (QUAD spi - qio) PSRAM 2Mb (QUAD spi - qio)  - 512KB SRAM, 384KB ROM - Xtensa 32-bit LX7 dual-core at 240 MHz - Adopts ESP32-S3R2
;default_envs = WAVESHARE_ESP32_C3_ZERO_N4      ;ESP32C3 Mini  - FLASH 4Mb  (QUAD spi - qio) NO PSRAM                    - 400KB SRAM, 384KB ROM - RISC-V 32-bit single-core at 160MHz    - Adopts ESP32-C3FH4
;default_envs = ESP32_WROOM_32                  ;ESP32 Wroom   - FLASH 4Mb  (QUAD spi - qio) NO PSRAM                    - 520KB SRAM, 448KB ROM - Xtensa 32-bit LX6 dual-core at 240 MHz - Adopts ESP32
; Le impostazioni globali delle cartelle vanno qui!
boards_dir = ../shared_boards

[env]

[esp32]
platform_packages = 

[common]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.38-1 ; Arduino Release v3.3.8 based on ESP-IDF v5.5.4
;platform = https://github.com/pioarduino/platform-espressif32.git#55.03.38 ; Arduino Release v3.3.8 based on ESP-IDF v5.5.4
; dalla versione 55.03.38 serve la versione del core di Platformio 6.1.19 - (usare dal terminale di PlatformIO Core CLI il comando:pio upgrade) https://github.com/platformio/platformio-core/releases/tag/v6.1.19
;platform = https://github.com/pioarduino/platform-espressif32.git#55.03.37

lib_deps = 
	;adafruit/Adafruit ST7735 and ST7789 Library @1.11.0
	Adafruit TinyUSB Library = https://github.com/adafruit/Adafruit_TinyUSB_Arduino.git#3.7.5
    ;Adafruit TinyUSB Library = https://github.com/adafruit/Adafruit_TinyUSB_Arduino.git#3.7.4
    ;LovyanGFX Library = https://github.com/lovyan03/LovyanGFX.git#1.2.19

build_unflags = 
	-std=gnu++11
	-std=gnu11
    -Og

build_flags = 
	;-D DEBUG_OPENFIRE
    -D PEDAL
	-D USE_TINYUSB
    ;-D USE_LOVYAN_GFX
	-std=gnu++17
	-std=gnu17
    -O2
	
[display_ESP32_S3_WROOM1_DevKitC_1]
build_unflags = 

build_flags = 
    -D PIN_LED1=-1
    -D PIN_LED2=-1
    -D PIN_LED3=-1
    -D PIN_LED4=-1

[display_WAVESHARE_ESP32_S3_PICO]
build_unflags = 

build_flags = 
    -D PIN_LED1=-1
    -D PIN_LED2=-1
    -D PIN_LED3=-1
    -D PIN_LED4=-1

[display_WAVESHARE_ESP32_S3_ZERO]
build_unflags = 

build_flags = 
    -D PIN_LED1=4
    -D PIN_LED2=5
    -D PIN_LED3=6
    -D PIN_LED4=7
	-D PIN_PEDAL=8
	-D PIN_PEDAL2=9

[display_WAVESHARE_ESP32_C3_ZERO]
build_unflags = 

build_flags = 
    -D PIN_LED1=-1
    -D PIN_LED2=-1
    -D PIN_LED3=-1
    -D PIN_LED4=-1

[env:ESP32_S3_WROOM1_DevKitC_1_N16R8]
platform = ${common.platform}
;board = esp32-s3-devkitc-1
board = ESP32-S3-WROOM-1-DevKitC-1-N16R8
framework = arduino
monitor_speed = 9600 ;115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	-D ARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${display_ESP32_S3_WROOM1_DevKitC_1.build_unflags}
build_flags = 
	-D ARDUINO_ESP32_S3_WROOM1_DevKitC_1_N16R8
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    ;-D OPENFIRE_ESPNOW_WIFI_POWER_AUTO ; solo per motivi di test
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	;-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${display_ESP32_S3_WROOM1_DevKitC_1.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_16MB.csv
;board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:ESP32_S3_WROOM1_DevKitC_1_N8R2]
platform = ${common.platform}
;board = esp32-s3-devkitc-1
board = ESP32-S3-WROOM-1-DevKitC-1-N8R2
framework = arduino
monitor_speed = 9600 ;115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	-D ARDUINO_USB_MODE=1
    ;-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${display_ESP32_S3_WROOM1_DevKitC_1.build_unflags}
build_flags = 
	-D ARDUINO_ESP32_S3_WROOM1_DevKitC_1_N8R2
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    ;-D OPENFIRE_ESPNOW_WIFI_POWER_AUTO ; solo per motivi di test
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	;-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${display_ESP32_S3_WROOM1_DevKitC_1.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_8MB.csv
;board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_S3_PICO]
platform = ${common.platform}
board = WAVESHARE-ESP32-S3-PICO-N16R2
;board = ESP32-S3-WROOM-1-DevKitC-1-N16R8
framework = arduino
monitor_speed = 9600 ;115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	-D ARDUINO_USB_MODE=1
    ;-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${display_WAVESHARE_ESP32_S3_PICO.build_unflags}
build_flags = 
	-D ARDUINO_WAVESHARE_ESP32_S3_PICO
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    ;-D OPENFIRE_ESPNOW_WIFI_POWER_AUTO ; solo per motivi di test
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${display_WAVESHARE_ESP32_S3_PICO.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_16MB.csv
;board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_S3_ZERO_N8R8]
platform = ${common.platform}
board = WAVESHARE-ESP32-S3-ZERO-N8R8
framework = arduino
monitor_speed = 115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	-D ARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${display_WAVESHARE_ESP32_S3_ZERO.build_unflags}
build_flags = 
	-D ARDUINO_WAVESHARE_ESP32_S3_ZERO_N8R8
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    ;-D OPENFIRE_ESPNOW_WIFI_POWER_AUTO ; solo per motivi di test
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	;-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${display_WAVESHARE_ESP32_S3_ZERO.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_8MB.csv
;board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_S3_ZERO_N4R2]
platform = ${common.platform}
board = WAVESHARE-ESP32-S3-ZERO-N4R2
framework = arduino
monitor_speed = 115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	-D ARDUINO_USB_MODE=1
    ;-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${display_WAVESHARE_ESP32_S3_ZERO.build_unflags}
build_flags = 
	-D ARDUINO_WAVESHARE_ESP32_S3_ZERO_N4R2
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    ;-D OPENFIRE_ESPNOW_WIFI_POWER_AUTO ; solo per motivi di test
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	;-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${display_WAVESHARE_ESP32_S3_ZERO.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_4MB.csv
;board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict

[env:WAVESHARE_ESP32_C3_ZERO_N4]
platform = ${common.platform}
board = WAVESHARE-ESP32-C3-ZERO-N4
framework = arduino
monitor_speed = 115200
lib_deps = 
	${common.lib_deps}
build_unflags = 
	;-D ARDUINO_USB_MODE=1
    ;-DBOARD_HAS_PSRAM   ; (disabilita PSRAM) serve per utilizzare in sicurezza i pin gpio 35,36,37 che altrimenti vengo usati dalla PSRAM di 8Mb che è OCTAL spi - opi 
	${common.build_unflags}
	${display_WAVESHARE_ESP32_C3_ZERO.build_unflags}
build_flags = 
	-D ARDUINO_WAVESHARE_ESP32_C3_ZERO_N4
	-D OPENFIRE_WIRELESS_ENABLE
	-D OPENFIRE_WIRELESS_DEVICE_ESPNOW
	;-D OPENFIRE_ESPNOW_WIFI_POWER=68 ; se non viene messo questo flag viene impostata a 84
	;-D OPENFIRE_ESPNOW_WIFI_CHANNEL=12 ; se non viene messo questo flag viene impostata a 12
    ;-D OPENFIRE_ESPNOW_WIFI_POWER_AUTO ; solo per motivi di test
    -D OPENFIRE_AUTO_CHANNEL_ESPNOW_WIFI ; imposta la ricerca automatica del canale ideale per la trasmissione espnow
	-D OPENFIRE_USE_ESPNOW_UNIFIED_PACKET ; TRASMETTE SEMPRE TUTTI I PACCHETTI MOUSE, KEYBORD O JOYPAD INSIEME IN UNICO PACCHETTO
	;-D ARDUINO_USB_MODE=0
	;-D ARDUINO_USB_CDC_ON_BOOT=1
	;-D USES_DISPLAY
	;-D DUAL_CORE
	${common.build_flags}
	${display_WAVESHARE_ESP32_C3_ZERO.build_flags}
platform_packages = ${esp32.platform_packages}
board_build.partitions = ../shared_boards/partitions/default_OF_4MB.csv
;board_build.filesystem = littlefs ; DICE A PLATFORMIO DI USARE LittleFS PER COPIARE I FILE DELLA DIRECTORY DATA DEL PROGETTO CON LA FUNZIONE UPLOAD SE SI VUOLE USARE
;boards_dir = ../shared_boards
lib_extra_dirs = ../shared_lib
lib_ldf_mode = chain
lib_compat_mode = strict