name: GLOBAL - OpenFIRE Build Package and Upload ALL

on:
  workflow_dispatch:
    inputs:
      sistemi_operativi:
        description: "Vuoi Creare anche i file per i sistemi operativi ? (necessario per creare release)"
        required: true
        default: "no"
        type: choice
        options:
          - "no"
          - "yes"
      release:
        description: "Vuoi creare una release globale ?"
        required: true
        default: "no"
        type: choice
        options:
          - "no"
          - "yes"
      tag_name:
        description: "Tag della release (es. v1.2.0 - es. v6.0-RC6) (usato solo se release=yes)"
        required: false
        default: ""
      release_name:
        description: "Nome leggibile della release (es. v6.0-RC6 OpenFIRE Firmware ESP32 - GLOBAL Release)"
        required: false
        default: ""
      draft:
        description: "Vuoi impostare la release come DRAFT? (false = NO, pubblica subito  - true = SI, lascialo in draft mode)"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"  
      prerelease:
        description: "E' una pre-release ? (false = NO  - true = SI, imposta il flag pre-release)"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"  

permissions:
  contents: write

jobs:
  # ==========================================
  # 1. BUILD FIRMWARE (PARALLELO)
  # ==========================================
  build_lightgun:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    name: Build LIGHTGUN
    strategy:
      matrix:
        include:
          - name: 'ESP32_S3_WROOM1_DevKitC_1_N16R8' 
            boards: 'ESP32_S3_WROOM1_DevKitC_1_N16R8'
            chip: 'esp32s3'
            flash_size: '16MB'
            flash_mode: 'dio'
            flash_freq: '80m'
            address_littleFS: '0xc90000'
          - name: 'WAVESHARE_ESP32_S3_PICO' 
            boards: 'WAVESHARE_ESP32_S3_PICO'
            chip: 'esp32s3'
            flash_size: '16MB'
            flash_mode: 'dio'
            flash_freq: '80m'       
            address_littleFS: '0xc90000'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio rich_click intelhex
      - uses: actions/cache@v5
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - if: (matrix.chip == 'esp32s3')
        run: |
          cd lightgun
          pio run -e ${{ matrix.boards }}
          pio run -e ${{ matrix.boards }} -t buildfs
          python ~/.platformio/packages/tool-esptoolpy/esptool.py --chip ${{ matrix.chip }} merge_bin -o OpenFIRE-LIGHTGUN-${{ matrix.boards }}.bin --flash_mode ${{ matrix.flash_mode }} --flash_size ${{ matrix.flash_size }} \
            0x0000 .pio/build/${{ matrix.boards }}/bootloader.bin \
            0x8000 .pio/build/${{ matrix.boards }}/partitions.bin \
            0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin \
            0x10000 .pio/build/${{ matrix.boards }}/firmware.bin \
            ${{ matrix.address_littleFS }} .pio/build/${{ matrix.boards }}/littlefs.bin
          python ~/.platformio/packages/tool-esptoolpy/esptool.py --chip ${{ matrix.chip }} merge_bin -o OpenFIRE-LIGHTGUN-NoFS-${{ matrix.boards }}.bin --flash_mode ${{ matrix.flash_mode }} --flash_size ${{ matrix.flash_size }} \
            0x0000 .pio/build/${{ matrix.boards }}/bootloader.bin \
            0x8000 .pio/build/${{ matrix.boards }}/partitions.bin \
            0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin \
            0x10000 .pio/build/${{ matrix.boards }}/firmware.bin
      - uses: actions/upload-artifact@v7
        with:
          name: OpenFIRE-LIGHTGUN-${{ matrix.boards }}
          path: lightgun/OpenFIRE-LIGHTGUN-${{ matrix.boards }}.bin
          if-no-files-found: error
      - uses: actions/upload-artifact@v7
        with:
          name: OpenFIRE-LIGHTGUN-NoFS-${{ matrix.boards }}
          path: lightgun/OpenFIRE-LIGHTGUN-NoFS-${{ matrix.boards }}.bin
          if-no-files-found: error

  build_dongle:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    name: Build DONGLE
    strategy:
      matrix:
        include:
          - name: 'ESP32_S3_WROOM1_DevKitC_1_N16R8' 
            boards: 'ESP32_S3_WROOM1_DevKitC_1_N16R8'
            chip: 'esp32s3'
            flash_size: '16MB'
            flash_mode: 'dio'
            flash_freq: '80m'
          - name: 'WAVESHARE_ESP32_S3_PICO' 
            boards: 'WAVESHARE_ESP32_S3_PICO'
            chip: 'esp32s3'
            flash_size: '16MB'
            flash_mode: 'dio'
            flash_freq: '80m'       
          - name: 'LILYGO_T_DONGLE_S3' 
            boards: 'LILYGO_T_DONGLE_S3'
            chip: 'esp32s3'
            flash_size: '16MB'
            flash_mode: 'dio'
            flash_freq: '80m'       
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio rich_click intelhex
      - uses: actions/cache@v5
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - if: (matrix.chip == 'esp32s3')
        run: |
          cd dongle
          pio run -e ${{ matrix.boards }}
          python ~/.platformio/packages/tool-esptoolpy/esptool.py --chip ${{ matrix.chip }} merge_bin -o OpenFIRE-DONGLE-${{ matrix.boards }}.bin --flash_mode ${{ matrix.flash_mode }} --flash_size ${{ matrix.flash_size }} \
            0x0000 .pio/build/${{ matrix.boards }}/bootloader.bin \
            0x8000 .pio/build/${{ matrix.boards }}/partitions.bin \
            0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin \
            0x10000 .pio/build/${{ matrix.boards }}/firmware.bin
      - uses: actions/upload-artifact@v7
        with:
          name: OpenFIRE-DONGLE-${{ matrix.boards }}
          path: dongle/OpenFIRE-DONGLE-${{ matrix.boards }}.bin
          if-no-files-found: error

  build_pedal:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    name: Build PEDAL
    strategy:
      matrix:
        include:
          - name: 'ESP32_S3_WROOM1_DevKitC_1_N16R8' 
            boards: 'ESP32_S3_WROOM1_DevKitC_1_N16R8'
            chip: 'esp32s3'
            flash_size: '16MB'
            flash_mode: 'dio'
            flash_freq: '80m'
          - name: 'WAVESHARE_ESP32_S3_PICO' 
            boards: 'WAVESHARE_ESP32_S3_PICO'
            chip: 'esp32s3'
            flash_size: '16MB'
            flash_mode: 'dio'
            flash_freq: '80m'       
          - name: 'LILYGO_T_DONGLE_S3' 
            boards: 'LILYGO_T_DONGLE_S3'
            chip: 'esp32s3'
            flash_size: '16MB'
            flash_mode: 'dio'
            flash_freq: '80m'       
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio rich_click intelhex
      - uses: actions/cache@v5
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - if: (matrix.chip == 'esp32s3')
        run: |
          cd pedal
          pio run -e ${{ matrix.boards }}
          python ~/.platformio/packages/tool-esptoolpy/esptool.py --chip ${{ matrix.chip }} merge_bin -o OpenFIRE-PEDAL-${{ matrix.boards }}.bin --flash_mode ${{ matrix.flash_mode }} --flash_size ${{ matrix.flash_size }} \
            0x0000 .pio/build/${{ matrix.boards }}/bootloader.bin \
            0x8000 .pio/build/${{ matrix.boards }}/partitions.bin \
            0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin \
            0x10000 .pio/build/${{ matrix.boards }}/firmware.bin
      - uses: actions/upload-artifact@v7
        with:
          name: OpenFIRE-PEDAL-${{ matrix.boards }}
          path: pedal/OpenFIRE-PEDAL-${{ matrix.boards }}.bin
          if-no-files-found: error

  # ==========================================
  # 2. PACKAGE ASSETS (PARALLELO)
  # ==========================================
  package_lightgun:
    needs: build_lightgun
    if: ${{ github.event.inputs.sistemi_operativi == 'yes' }}
    runs-on: ${{ matrix.os_config.runner }}
    strategy:
      matrix:
        boards:
          - { name: 'ESP32_S3_WROOM1_DevKitC_1_N16R8', chip: 'esp32s3', flash_mode: 'dio', flash_freq: '80m' }
          - { name: 'WAVESHARE_ESP32_S3_PICO', chip: 'esp32s3', flash_mode: 'dio', flash_freq: '80m' }
        os_config:
          - { name: windows-64bit, runner: windows-latest, esptool_url: 'https://github.com/espressif/esptool/releases/download/v5.1.0/esptool-v5.1.0-windows-amd64.zip', esptool_tipo_file: zip, esptool_path_in_zip: 'esptool-windows-amd64/', esptool_filename_in_zip: 'esptool.exe', script_name: 'flash_firmware.bat' }
          - { name: linux-amd-64bit, runner: ubuntu-latest, esptool_url: 'https://github.com/espressif/esptool/releases/download/v5.1.0/esptool-v5.1.0-linux-amd64.tar.gz', esptool_tipo_file: tar.gz, esptool_path_in_zip: 'esptool-linux-amd64/', esptool_filename_in_zip: 'esptool', script_name: 'flash_firmware.sh' }
          - { name: macos-64bit, runner: macos-latest, esptool_url: 'https://github.com/espressif/esptool/releases/download/v5.1.0/esptool-v5.1.0-macos-amd64.tar.gz', esptool_tipo_file: tar.gz, esptool_path_in_zip: 'esptool-macos-amd64/', esptool_filename_in_zip: 'esptool', script_name: 'flash_firmware.sh' }
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: OpenFIRE-LIGHTGUN-${{ matrix.boards.name }}
          path: ./downloaded_firmware
      - uses: actions/download-artifact@v8
        with:
          name: OpenFIRE-LIGHTGUN-NoFS-${{ matrix.boards.name }}
          path: ./downloaded_firmware
      - shell: bash
        run: |
          mkdir staging_dir
          mv ./downloaded_firmware/OpenFIRE-LIGHTGUN-${{ matrix.boards.name }}.bin ./staging_dir/firmware.bin
          mv ./downloaded_firmware/OpenFIRE-LIGHTGUN-NoFS-${{ matrix.boards.name }}.bin ./staging_dir/firmware-NoFS.bin
      - shell: bash 
        run: |
          if [[ "${{ matrix.os_config.esptool_tipo_file }}" == "zip" ]]; then curl -L -o esptool_archive.zip "${{ matrix.os_config.esptool_url }}"; unzip -j esptool_archive.zip "${{ matrix.os_config.esptool_path_in_zip }}${{ matrix.os_config.esptool_filename_in_zip }}" -d staging_dir; fi
          if [[ "${{ matrix.os_config.esptool_tipo_file }}" == "tar.gz" ]]; then curl -L -o esptool_archive.tar.gz "${{ matrix.os_config.esptool_url }}"; tar -xzf esptool_archive.tar.gz -C staging_dir --strip-components=1 "${{ matrix.os_config.esptool_path_in_zip }}${{ matrix.os_config.esptool_filename_in_zip }}"; fi
          if [[ "${{ matrix.os_config.name }}" == "linux-amd-64bit" || "${{ matrix.os_config.name }}" == "macos-64bit" ]]; then chmod +x "staging_dir/${{ matrix.os_config.esptool_filename_in_zip }}"; fi
      - shell: bash 
        run: |
          SCRIPT_PATH="staging_dir/${{ matrix.os_config.script_name }}"
          if [[ "${{ matrix.os_config.name }}" == "windows-64bit" ]]; then
          cat <<EOF > "$SCRIPT_PATH"
          @echo off
          echo Flashing OpenFIRE LIGHTGUN Firmware for board: ${{ matrix.boards.name }}
          set FIRMWARE_FILE=firmware-NoFS.bin
          set /p FIRMWARE_CHOICE="If you want to flash the firmware with the entire filesystem type '1': "
          if "%FIRMWARE_CHOICE%"=="1" set FIRMWARE_FILE=firmware.bin
          ${{ matrix.os_config.esptool_filename_in_zip }} --chip ${{ matrix.boards.chip }} --baud 460800 write-flash -z --flash-mode ${{ matrix.boards.flash_mode }} --flash-freq ${{ matrix.boards.flash_freq }} 0x0000 %FIRMWARE_FILE%
          pause
          EOF
          else
          cat <<EOF > "$SCRIPT_PATH"
          #!/bin/bash
          echo "Flashing OpenFIRE LIGHTGUN Firmware for board: ${{ matrix.boards.name }}"
          FIRMWARE_FILE="firmware-NoFS.bin"
          read -r -p "If you want to flash the firmware with the entire filesystem type '1': " FIRMWARE_CHOICE
          if [[ \$FIRMWARE_CHOICE == "1" ]]; then FIRMWARE_FILE="firmware.bin"; fi
          ./${{ matrix.os_config.esptool_filename_in_zip }} --chip ${{ matrix.boards.chip }} --baud 460800 write-flash -z --flash-mode ${{ matrix.boards.flash_mode }} --flash-freq ${{ matrix.boards.flash_freq }} 0x0000 \$FIRMWARE_FILE
          EOF
          chmod +x "$SCRIPT_PATH"
          fi
      - shell: bash
        run: |
          ARCHIVE_FILENAME="OpenFIRE-LIGHTGUN-${{ matrix.boards.name }}-${{ matrix.os_config.name }}.zip"
          if [[ "${{ matrix.os_config.name }}" == "windows-64bit" ]]; then
            powershell -Command "Compress-Archive -Path staging_dir\* -DestinationPath ${{ github.workspace }}/$ARCHIVE_FILENAME -Force"
          else
            (cd staging_dir && zip -r "${{ github.workspace }}/$ARCHIVE_FILENAME" .)
          fi
      - uses: actions/upload-artifact@v7
        with:
          name: OpenFIRE-LIGHTGUN-${{ matrix.boards.name }}-${{ matrix.os_config.name }}.zip
          path: ${{ github.workspace }}/OpenFIRE-LIGHTGUN-${{ matrix.boards.name }}-${{ matrix.os_config.name }}.zip

  package_dongle:
    needs: build_dongle
    if: ${{ github.event.inputs.sistemi_operativi == 'yes' }}
    runs-on: ${{ matrix.os_config.runner }}
    strategy:
      matrix:
        boards:
          - { name: 'ESP32_S3_WROOM1_DevKitC_1_N16R8', chip: 'esp32s3', flash_mode: 'dio', flash_freq: '80m' }
          - { name: 'WAVESHARE_ESP32_S3_PICO', chip: 'esp32s3', flash_mode: 'dio', flash_freq: '80m' }
          - { name: 'LILYGO_T_DONGLE_S3', chip: 'esp32s3', flash_mode: 'dio', flash_freq: '80m' }
        os_config:
          - { name: windows-64bit, runner: windows-latest, esptool_url: 'https://github.com/espressif/esptool/releases/download/v5.1.0/esptool-v5.1.0-windows-amd64.zip', esptool_tipo_file: zip, esptool_path_in_zip: 'esptool-windows-amd64/', esptool_filename_in_zip: 'esptool.exe', script_name: 'flash_firmware.bat' }
          - { name: linux-amd-64bit, runner: ubuntu-latest, esptool_url: 'https://github.com/espressif/esptool/releases/download/v5.1.0/esptool-v5.1.0-linux-amd64.tar.gz', esptool_tipo_file: tar.gz, esptool_path_in_zip: 'esptool-linux-amd64/', esptool_filename_in_zip: 'esptool', script_name: 'flash_firmware.sh' }
          - { name: macos-64bit, runner: macos-latest, esptool_url: 'https://github.com/espressif/esptool/releases/download/v5.1.0/esptool-v5.1.0-macos-amd64.tar.gz', esptool_tipo_file: tar.gz, esptool_path_in_zip: 'esptool-macos-amd64/', esptool_filename_in_zip: 'esptool', script_name: 'flash_firmware.sh' }
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: OpenFIRE-DONGLE-${{ matrix.boards.name }}
          path: ./downloaded_firmware
      - shell: bash
        run: |
          mkdir staging_dir
          mv ./downloaded_firmware/OpenFIRE-DONGLE-${{ matrix.boards.name }}.bin ./staging_dir/firmware.bin
      - shell: bash 
        run: |
          if [[ "${{ matrix.os_config.esptool_tipo_file }}" == "zip" ]]; then curl -L -o esptool_archive.zip "${{ matrix.os_config.esptool_url }}"; unzip -j esptool_archive.zip "${{ matrix.os_config.esptool_path_in_zip }}${{ matrix.os_config.esptool_filename_in_zip }}" -d staging_dir; fi
          if [[ "${{ matrix.os_config.esptool_tipo_file }}" == "tar.gz" ]]; then curl -L -o esptool_archive.tar.gz "${{ matrix.os_config.esptool_url }}"; tar -xzf esptool_archive.tar.gz -C staging_dir --strip-components=1 "${{ matrix.os_config.esptool_path_in_zip }}${{ matrix.os_config.esptool_filename_in_zip }}"; fi
          if [[ "${{ matrix.os_config.name }}" == "linux-amd-64bit" || "${{ matrix.os_config.name }}" == "macos-64bit" ]]; then chmod +x "staging_dir/${{ matrix.os_config.esptool_filename_in_zip }}"; fi
      - shell: bash 
        run: |
          SCRIPT_PATH="staging_dir/${{ matrix.os_config.script_name }}"
          if [[ "${{ matrix.os_config.name }}" == "windows-64bit" ]]; then
          cat <<EOF > "$SCRIPT_PATH"
          @echo off
          echo Flashing OpenFIRE DONGLE Firmware for board: ${{ matrix.boards.name }}
          ${{ matrix.os_config.esptool_filename_in_zip }} --chip ${{ matrix.boards.chip }} --baud 460800 write-flash -z --flash-mode ${{ matrix.boards.flash_mode }} --flash_freq ${{ matrix.boards.flash_freq }} 0x0000 firmware.bin
          pause
          EOF
          else
          cat <<EOF > "$SCRIPT_PATH"
          #!/bin/bash
          ./${{ matrix.os_config.esptool_filename_in_zip }} --chip ${{ matrix.boards.chip }} --baud 460800 write-flash -z --flash-mode ${{ matrix.boards.flash_mode }} --flash_freq ${{ matrix.boards.flash_freq }} 0x0000 firmware.bin
          EOF
          chmod +x "$SCRIPT_PATH"
          fi
      - shell: bash
        run: |
          ARCHIVE_FILENAME="OpenFIRE-DONGLE-${{ matrix.boards.name }}-${{ matrix.os_config.name }}.zip"
          if [[ "${{ matrix.os_config.name }}" == "windows-64bit" ]]; then
            powershell -Command "Compress-Archive -Path staging_dir\* -DestinationPath ${{ github.workspace }}/$ARCHIVE_FILENAME -Force"
          else
            (cd staging_dir && zip -r "${{ github.workspace }}/$ARCHIVE_FILENAME" .)
          fi
      - uses: actions/upload-artifact@v7
        with:
          name: OpenFIRE-DONGLE-${{ matrix.boards.name }}-${{ matrix.os_config.name }}.zip
          path: ${{ github.workspace }}/OpenFIRE-DONGLE-${{ matrix.boards.name }}-${{ matrix.os_config.name }}.zip

  package_pedal:
    needs: build_pedal
    if: ${{ github.event.inputs.sistemi_operativi == 'yes' }}
    runs-on: ${{ matrix.os_config.runner }}
    strategy:
      matrix:
        boards:
          - { name: 'ESP32_S3_WROOM1_DevKitC_1_N16R8', chip: 'esp32s3', flash_mode: 'dio', flash_freq: '80m' }
          - { name: 'WAVESHARE_ESP32_S3_PICO', chip: 'esp32s3', flash_mode: 'dio', flash_freq: '80m' }
          - { name: 'LILYGO_T_DONGLE_S3', chip: 'esp32s3', flash_mode: 'dio', flash_freq: '80m' }
        os_config:
          - { name: windows-64bit, runner: windows-latest, esptool_url: 'https://github.com/espressif/esptool/releases/download/v5.1.0/esptool-v5.1.0-windows-amd64.zip', esptool_tipo_file: zip, esptool_path_in_zip: 'esptool-windows-amd64/', esptool_filename_in_zip: 'esptool.exe', script_name: 'flash_firmware.bat' }
          - { name: linux-amd-64bit, runner: ubuntu-latest, esptool_url: 'https://github.com/espressif/esptool/releases/download/v5.1.0/esptool-v5.1.0-linux-amd64.tar.gz', esptool_tipo_file: tar.gz, esptool_path_in_zip: 'esptool-linux-amd64/', esptool_filename_in_zip: 'esptool', script_name: 'flash_firmware.sh' }
          - { name: macos-64bit, runner: macos-latest, esptool_url: 'https://github.com/espressif/esptool/releases/download/v5.1.0/esptool-v5.1.0-macos-amd64.tar.gz', esptool_tipo_file: tar.gz, esptool_path_in_zip: 'esptool-macos-amd64/', esptool_filename_in_zip: 'esptool', script_name: 'flash_firmware.sh' }
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: OpenFIRE-PEDAL-${{ matrix.boards.name }}
          path: ./downloaded_firmware
      - shell: bash
        run: |
          mkdir staging_dir
          mv ./downloaded_firmware/OpenFIRE-PEDAL-${{ matrix.boards.name }}.bin ./staging_dir/firmware.bin
      - shell: bash 
        run: |
          if [[ "${{ matrix.os_config.esptool_tipo_file }}" == "zip" ]]; then curl -L -o esptool_archive.zip "${{ matrix.os_config.esptool_url }}"; unzip -j esptool_archive.zip "${{ matrix.os_config.esptool_path_in_zip }}${{ matrix.os_config.esptool_filename_in_zip }}" -d staging_dir; fi
          if [[ "${{ matrix.os_config.esptool_tipo_file }}" == "tar.gz" ]]; then curl -L -o esptool_archive.tar.gz "${{ matrix.os_config.esptool_url }}"; tar -xzf esptool_archive.tar.gz -C staging_dir --strip-components=1 "${{ matrix.os_config.esptool_path_in_zip }}${{ matrix.os_config.esptool_filename_in_zip }}"; fi
          if [[ "${{ matrix.os_config.name }}" == "linux-amd-64bit" || "${{ matrix.os_config.name }}" == "macos-64bit" ]]; then chmod +x "staging_dir/${{ matrix.os_config.esptool_filename_in_zip }}"; fi
      - shell: bash
        run: |
          ARCHIVE_FILENAME="OpenFIRE-PEDAL-${{ matrix.boards.name }}-${{ matrix.os_config.name }}.zip"
          if [[ "${{ matrix.os_config.name }}" == "windows-64bit" ]]; then
            powershell -Command "Compress-Archive -Path staging_dir\* -DestinationPath ${{ github.workspace }}/$ARCHIVE_FILENAME -Force"
          else
            (cd staging_dir && zip -r "${{ github.workspace }}/$ARCHIVE_FILENAME" .)
          fi
      - uses: actions/upload-artifact@v7
        with:
          name: OpenFIRE-PEDAL-${{ matrix.boards.name }}-${{ matrix.os_config.name }}.zip
          path: ${{ github.workspace }}/OpenFIRE-PEDAL-${{ matrix.boards.name }}-${{ matrix.os_config.name }}.zip

  # ==========================================
  # 3. CREAZIONE DELLA RELEASE GLOBALE
  # ==========================================
  create_global_release:
    needs: [package_lightgun, package_dongle, package_pedal]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.release == 'yes' && github.event.inputs.sistemi_operativi == 'yes' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6 # Fondamentale per leggere GLOBAL_template.md

      - name: Prepare GLOBAL Release Body
        id: prepare_body
        run: |
          TEMPLATE_PATH=".github/release_templates/GLOBAL_template.md"
          
          # Sostituisce <TAG> con il valore inserito nel trigger
          sed "s/<TAG>/${{ github.event.inputs.tag_name }}/g" "$TEMPLATE_PATH" > final_body.md
          
          # Carica il contenuto in GITHUB_ENV gestendo correttamente i ritorni a capo
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          cat final_body.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Download ALL artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./release_assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          body: ${{ env.RELEASE_BODY }} # <--- Usa il corpo generato dal template globale
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ALL assets to Release
        run: |
          find ./release_assets -type f -print0 | while IFS= read -r -d '' file; do
            echo "Uploading $file"
            gh release upload ${{ github.event.inputs.tag_name }} "$file" --clobber --repo ${{ github.repository }}
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}